name: base runner

description: install the macOS CI toolchain

runs:
  using: composite
  steps:
    - name: install ci toolchain
      shell: bash
      run: |
        set -euo pipefail
        brew install \
          ninja \
          sox \
          llvm \
          cppcheck \
          shellcheck \
          just
        echo "$(brew --prefix llvm)/bin" >> "${GITHUB_PATH}"
