name: shellcheck

on:
  workflow_call:

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: shellcheck
        run: just sc
