name: format

on:
  workflow_call:

permissions:
  contents: read

jobs:
  format:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: format check
        run: just fc
