name: runtime safety

on:
  workflow_call:

permissions:
  contents: read

jobs:
  sanitizers:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: base runner
        uses: ./.github/actions/base-runner

      - name: install
        run: bash ./scripts/install

      - name: runtime safety
        run: just s
